virt: lxd
os: linux
dist: focal
language: python
python: "3.8"

addons:
  apt:
    packages:
      - graphviz

install:
  - pip -q install mkdocs mkdocs-windmill markdown_inline_graphviz_extension
script:
  - shellcheck build.sh
  - sh build.sh
