virt: lxd
os: linux
dist: focal
language: python
python: "3.8"

addons:
  apt:
    packages:
      - graphviz

install:
  - pip -q install mkdocs mkdocs-windmill
  - pip -q install markdown_inline_graphviz_extension
  - pip -q install markdown-inline-graphviz-extension-png
script:
  - shellcheck build.sh
  - sh build.sh
